name: C++ CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ libboost-all-dev libcurl4-openssl-dev pybind11-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: ctest -V # Assuming Google Test is set up by C++-dev
